export const MAMBOG_II_SUBDIVISIONS = [
  "Addas Village",
  "Breezewood 1 / Breezewood Phase 1",
  "Breeze Woods 1",
  "Breeze Woods 3",
  "Bresciamolino 3",
  "Cherry Homes Phase IV / Cherry Homes Ph4",
  "Cherry Homes Subdivision",
  "Citta Italia",
  "Citta Lessina",
  "Evertown Village",
  "Grand Strike Ville / Grand Strikeville 4 / Strikeville IV",
  "Green Plain Village / Greenplain Village",
  "Greenplain Village - Eduardo Sabater",
  "Green Square Villas",
  "Green Town Villas",
  "Green Town Villas 1 Extension",
  "Greetown Homes / Greentown Village 1",
  "Mambog Homeowners Association",
  "Mambog Ville HOA",
  "Napoli di Citta Italia",
  "Palermo de Citta Italia",
  "Parkdale 1",
  "Parkdale 2",
  "Perpetual Village 7 Phase 1",
  "RCD Subdivision / RCD Realty & Corp.",
  "Sampaguita Village",
  "Sampaguita Village II / Melo Property",
  "Shinjuska Townhomes",
  "Silver Homes Classic",
  "Springside Subdivision",
  "Springside Villas",
  "Valleyfield Subdivision",
  "Venezia",
  "Vicenzia",
  "Villa Arsenia 1",
  "Villa Arsenia 2",
  "Villa Arsenia 3",
  "Villa Primarosa Subdivision",
  "Vista Verde Phase 1",
  "Vista Verde Phase 2",
  "Vista Verde Phase 4",
  "WH Land Subdivision",
];
